import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { beforeAll,afterAll,beforeEach,it,expect } from 'vitest';
import { readWorkspace,writeWorkspace,publicWorkspace,setContentState } from './workspace.mjs';
import { commerceAction,commerceWorkspace,startOutreachDraft } from './commerce-workspace.mjs';
import { productScope } from './product-scope.mjs';
import { importSignals,reviewSignal,saveAccount,recordInquiry,leadAction,generateContactSuggestion,preparePublication } from './acquisition-workspace.mjs';
import { createAgent,saveAgent,startAgentTrial,agentAction } from './business-agents.mjs';
const root=process.cwd(),email='commerce@example.test';let dir;
const seed=()=>({customers:[{id:'c1',name:'照明业务',hunt:'其他行业',pitch:'照明产品',track:'存量',packs:[],drops:[]},{id:'c2',name:'同名业务',hunt:'其他行业',pitch:'另一业务',track:'存量',packs:[],drops:[]}],feedback:{},ledger:[],contentStates:{}});
const get=()=>commerceWorkspace(email).acquisition;
const action=(action,more={})=>commerceAction(email,{customerId:'c1',action,...more});
const createProduct=()=>{action('product',{name:'阅读灯',facts:'适用于书桌，使用插座',source:'产品说明书'});return get().products.at(-1);};
const signal=(extra={})=>({platform:'抖音',text:'想买不用打孔的灯，有推荐吗？',url:'https://www.douyin.com/video/123?comment=1',recordId:'comment1',authorId:'buyer1',authorName:'小夏',...extra});
const now=()=>new Date(Date.now()-1000).toISOString();
function source(){action('target',{name:'其他账号',url:'https://www.douyin.com/user/author1',platform:'抖音',recordId:'author1'});const t=get().targets[0];action('work',{targetId:t.id,title:'书桌照明怎么选',url:'https://www.douyin.com/video/123',recordId:'123',description:'讨论台灯与壁灯的安装条件'});return get().works[0];}
function lead(){const work=source();importSignals(email,{customerId:'c1',workId:work.id,source:'用户提供原评论',rows:[signal()]});reviewSignal(email,{signalId:get().signals[0].id,action:'confirm',note:'已核对求推荐原文'});return get().leads[0];}
function opportunity(l,productIds=[]){action('opportunity',{leadId:l.id,title:'书桌照明',productIds,skuIds:[],signalIds:l.signalIds,stage:'比较中',note:'依据原评论'});return get().opportunities.at(-1);}
async function setup(){const p=createProduct(),l=lead(),o=opportunity(l,[p.id]);saveAccount(email,{customerId:'c1',platform:'抖音',name:'自己的回复账号'});const account=get().accounts[0];createAgent(email,{customerId:'c1'});const ag=get().agents[0];saveAgent(email,{agentId:ag.id,baseVersion:1,config:{...ag.versions[0].config,criteria:'明确照明需求',bindings:[{accountId:account.id,enabled:true}]}});const job=startAgentTrial(email,{agentId:ag.id,signalId:l.signalIds[0]},{ready:()=>false});await job.completion;agentAction(email,{agentId:ag.id,action:'enable'});return {p,l,o,account,ag,input:{customerId:'c1',opportunityId:o.id,agentId:ag.id,accountId:account.id,channel:'评论',signalId:l.signalIds[0]}};}
beforeAll(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'harta-commerce-'));fs.symlinkSync(path.join(root,'vendor'),path.join(dir,'vendor'));process.chdir(dir);});
afterAll(()=>{process.chdir(root);fs.rmSync(dir,{recursive:true,force:true});});
beforeEach(()=>writeWorkspace(email,seed()));
it('product and SKU ownership, mandatory provenance and optimistic edits',()=>{const p=createProduct();expect(()=>action('sku',{productId:p.id,name:'白色',priceTerms:'100 元'})).toThrow('来源');action('sku',{productId:p.id,name:'白色',priceTerms:'100 元/台，门店报价',source:'人工确认'});const sku=get().skus[0];expect(()=>productScope(readWorkspace(email),'c2',{productIds:[p.id]})).toThrow('业务');expect(()=>productScope(readWorkspace(email),'c1',{skuIds:[sku.id]})).toThrow('规格');expect(()=>action('product',{id:p.id,baseRevision:0,name:'覆盖'})).toThrow('变化');expect(get().products[0].name).toBe('阅读灯');expect(()=>commerceAction('other@example.test',{action:'product',customerId:'c1',name:'越权'})).toThrow('业务');});
it('single service can have no SKU and multiple product scope does not include other catalog facts',()=>{const p=createProduct();action('product',{name:'秘密产品',facts:'秘密售价',source:'资料'});const scope=productScope(readWorkspace(email),'c1',{productIds:[p.id]});expect(scope.skus).toEqual([]);expect(scope.text).not.toContain('秘密售价');expect(productScope(readWorkspace(email),'c1',{}).text).toBe('');});
it('source account != owned sender; author identity is derived and excluded',()=>{const work=source();importSignals(email,{customerId:'c1',workId:work.id,source:'原文',rows:[signal(),signal({recordId:'reply1',authorId:'author1',parentRecordId:'comment1',text:'作者回复'})]});expect(get().signals[1].isAuthorReply).toBe(true);expect(()=>reviewSignal(email,{signalId:get().signals[1].id,action:'confirm',note:'强行确认'})).toThrow('作者');expect(get().accounts).toHaveLength(0);expect(()=>importSignals(email,{customerId:'c2',workId:work.id,source:'原文',rows:[signal()]})).toThrow('业务');});
it('comment import rejects cyclic replies and partial invalid batches without writes',()=>{const work=source();expect(()=>importSignals(email,{customerId:'c1',workId:work.id,source:'原文',rows:[signal({recordId:'a',parentRecordId:'b'}),signal({recordId:'b',parentRecordId:'a'})]})).toThrow('循环');expect(get().signals).toHaveLength(0);expect(()=>importSignals(email,{customerId:'c1',workId:work.id,source:'原文',rows:[signal(),signal({url:'javascript:alert(1)'})]})).toThrow();expect(get().signals).toHaveLength(0);});
it('source duplicates are idempotent and stable identities do not duplicate people',()=>{const l=lead(),w=get().works[0];importSignals(email,{customerId:'c1',workId:w.id,source:'重读',rows:[signal(),signal({recordId:'comment2'})]});expect(get().signals).toHaveLength(2);reviewSignal(email,{signalId:get().signals[1].id,action:'confirm',note:'同一人补充需求'});expect(get().leads).toHaveLength(1);expect(get().leads[0].id).toBe(l.id);expect(()=>action('target',{name:'重复',platform:'抖音',url:get().targets[0].url})).toThrow('已存在');});
it('same contact has independent purchase stages; no hidden legacy stage mutation',()=>{const l=lead(),one=opportunity(l);const two=opportunity(l);action('opportunity',{id:one.id,baseRevision:one.revision,leadId:l.id,title:one.title,stage:'已成交',note:'人工核对成交记录',productIds:[],skuIds:[],signalIds:l.signalIds});expect(get().opportunities.find(o=>o.id===two.id).stage).toBe('比较中');expect(get().leads[0].stage).toBe('值得跟进');expect(()=>action('opportunity',{id:one.id,baseRevision:one.revision,leadId:l.id,title:'过期提交',note:'依据'})).toThrow('变化');});
it('cannot enable automatic messaging by forging capability flags',async()=>{const {o}=await setup();for(const mode of ['auto','confirm'])expect(()=>action('mode',{opportunityId:o.id,mode,capabilities:{send:true,receive:true}})).toThrow('尚未验证');});
it('agent requires active binding and concrete original comment; templates never claim sent',async()=>{const {input,account}=await setup();expect(()=>startOutreachDraft(email,{...input,signalId:''})).toThrow('原评论');expect(()=>startOutreachDraft(email,{...input,accountId:get().targets[0].id})).toThrow('账号');const job=startOutreachDraft(email,input,{ready:()=>false});await job.completion;expect(get().outreachRuns.at(-1).status).toBe('limited');const m=get().leads[0].messages.at(-1);expect(m.status).toBe('draft');expect(m.accountId).toBe(account.id);expect(m.channel).toBe('评论');expect(m.productScope.products[0].name).toBe('阅读灯');});
it('handoff during generation discards late output and duplicate starts are blocked',async()=>{const {input,o}=await setup();let resolve;const job=startOutreachDraft(email,input,{ready:()=>true,chatFn:()=>new Promise(r=>resolve=r),review:async()=>[]});expect(()=>startOutreachDraft(email,input,{ready:()=>false})).toThrow('正在起草');action('handoff',{opportunityId:o.id,note:'需要人工'});resolve('请问书桌的位置固定吗？');await job.completion;expect(get().outreachRuns.at(-1).status).toBe('failed');expect(get().leads[0].messages).toHaveLength(0);});
it('agent pause, product changes and refusal invalidate copying; manual sends require evidence',async()=>{const {input,p,l,ag}=await setup();await startOutreachDraft(email,input,{ready:()=>false}).completion;let m=get().leads[0].messages.at(-1);agentAction(email,{agentId:ag.id,action:'pause'});expect(()=>leadAction(email,{leadId:l.id,messageId:m.id,action:'check-copy'})).toThrow('暂停');action('product',{id:p.id,baseRevision:p.revision,name:p.name,facts:'新事实',source:'新版说明书'});expect(get().leads[0].messages.at(-1).stale).toBe(true);expect(()=>leadAction(email,{leadId:l.id,messageId:m.id,action:'sent',confirmed:true})).toThrow('依据');leadAction(email,{leadId:l.id,action:'block',note:'对方拒绝联系'});expect(()=>leadAction(email,{leadId:l.id,messageId:m.id,action:'copy'})).toThrow('禁止');});
it('channel, account and need isolate incoming events and draft context',async()=>{const {l,o,p,account}=await setup(), other=opportunity(l);const inquiry={customerId:'c1',leadId:l.id,platform:'抖音',authorId:l.authorId,authorName:l.authorName,accountId:account.id,channel:'私信',text:'另一单的秘密信息',evidence:'原消息',receivedAt:now(),opportunityId:other.id};recordInquiry(email,inquiry);let request;await generateContactSuggestion(email,{leadId:l.id,opportunityId:o.id,accountId:account.id,channel:'私信'},{ready:()=>true,chatFn:async r=>{request=r;return '请说明安装条件';},review:async()=>[]});expect(request.user).not.toContain('另一单的秘密信息');expect(request.user).toContain(p.name);expect(()=>recordInquiry(email,{...inquiry,leadId:'not-this-contact'})).toThrow('联系人');});
it('product update flags drafts and blocks legacy publication shortcuts without changing history',()=>{const p=createProduct(),s=readWorkspace(email);const pack={id:'draft1',tier:'今日',copies:{},shells:{小红书:[{title:'原版本',body:'按说明书选择'}]},productScope:productScope(s,'c1',{productIds:[p.id]})};s.customers[0].drops.push(pack);writeWorkspace(email,s);action('product',{id:p.id,baseRevision:p.revision,name:p.name,facts:'新版参数',source:'新说明书'});const view=publicWorkspace(readWorkspace(email)),updated=view.customers[0].drops[0];expect(updated.productReview.required).toBe(true);expect(updated.shells.小红书[0].title).toBe('原版本');expect(setContentState(email,{packId:'draft1',keys:['draft1::x'],status:'published'}).error).toContain('资料');expect(()=>action('content-review',{packId:pack.id,confirmed:true,note:'已核对',scopeHash:'stale',contentHash:updated.productReview.contentHash})).toThrow('更新');action('content-review',{packId:pack.id,confirmed:true,note:'已核对正文，无参数承诺',scopeHash:updated.productReview.currentHash,contentHash:updated.productReview.contentHash});expect(publicWorkspace(readWorkspace(email)).customers[0].drops[0].productReview.required).toBe(false);expect(readWorkspace(email).customers[0].drops[0].productReviews[0].previous.products[0].facts).toContain('使用插座');});
it('new business skips service identity wizard and existing fields survive normalization',()=>{commerceAction(email,{action:'business',name:'自己的品牌',pitch:'照明产品',hunt:'其他行业'});expect(readWorkspace(email).customers).toHaveLength(3);const p=createProduct();const s=readWorkspace(email);s.customers[0].pitch='修改业务';writeWorkspace(email,s);expect(get().products[0].id).toBe(p.id);});
it('a duplicate platform message cannot be rebound to another need or contact',async()=>{const {l,o,account}=await setup(),other=opportunity(l);const input={customerId:'c1',leadId:l.id,platform:'抖音',authorId:l.authorId,authorName:l.authorName,accountId:account.id,channel:'私信',text:'书桌灯安装怎么处理',evidence:'原消息',receivedAt:now(),opportunityId:o.id,messageId:'platform-message-1'};recordInquiry(email,input);recordInquiry(email,input);expect(get().leads[0].messages).toHaveLength(1);expect(()=>recordInquiry(email,{...input,opportunityId:other.id})).toThrow('消息 ID');expect(()=>recordInquiry(email,{...input,leadId:'foreign'})).toThrow();expect(()=>recordInquiry(email,{...input,text:'另一段原文'})).toThrow('消息 ID');expect(get().leads[0].messages).toHaveLength(1);});
it('duplicate comment IDs across videos in the same batch fail atomically',()=>{const one=source();action('work',{targetId:one.targetId,title:'另一视频',url:'https://www.douyin.com/video/456',recordId:'456'});const two=get().works[1];expect(()=>importSignals(email,{customerId:'c1',source:'原文',rows:[signal({workId:one.id}),signal({workId:two.id})]})).toThrow('冲突');expect(get().signals).toHaveLength(0);});
it('provider errors cannot leak secrets via coincidental business keywords',async()=>{const {input}=await setup();await startOutreachDraft(email,input,{ready:()=>true,chatFn:async()=>{throw new Error('账号 token=secret-fixture');},review:async()=>[]}).completion;expect(get().outreachRuns[0].status).toBe('failed');expect(JSON.stringify(get().outreachRuns)).not.toContain('secret-fixture');});
it('outreach timeout rejects late output and leaves no sendable draft',async()=>{const {input}=await setup();let resolve;const job=startOutreachDraft(email,input,{ready:()=>true,chatFn:()=>new Promise(r=>resolve=r),review:async()=>[],timeoutMs:5});await job.completion;expect(get().outreachRuns[0].status).toBe('failed');expect(get().outreachRuns[0].error).toContain('时长');resolve('请说明你的安装条件');await new Promise(r=>setTimeout(r,10));expect(get().leads[0].messages).toHaveLength(0);});
it('late import of an older inquiry does not redirect a draft or clear newer unanswered messages',async()=>{const {l,o,account}=await setup();const input={customerId:'c1',leadId:l.id,platform:'抖音',authorId:l.authorId,authorName:l.authorName,accountId:account.id,channel:'私信',text:'新咨询',evidence:'原消息',receivedAt:'2026-01-02T10:00:00Z',opportunityId:o.id};recordInquiry(email,input);const newer=get().leads[0].messages[0];recordInquiry(email,{...input,text:'晚导入的旧消息',receivedAt:'2026-01-01T10:00:00Z'});leadAction(email,{leadId:l.id,opportunityId:o.id,accountId:account.id,channel:'私信',action:'draft',text:'请补充安装条件',recipient:l.authorId});let m=get().leads[0].messages.at(-1);expect(m.replyTo).toBe(newer.id);leadAction(email,{leadId:l.id,messageId:m.id,action:'sent',confirmed:true,sentAt:'2026-01-01T11:00:00Z',note:'之前实际发送记录'});expect(get().leads[0].needsReply).toBe(true);});
it('legacy contact takeover can be deliberately resumed without undoing refusal',async()=>{const {l,input}=await setup();leadAction(email,{leadId:l.id,action:'takeover'});expect(()=>startOutreachDraft(email,input,{ready:()=>false})).toThrow('接管');expect(()=>leadAction(email,{leadId:l.id,action:'resume-agent'})).toThrow('依据');leadAction(email,{leadId:l.id,action:'resume-agent',note:'人工确认可以恢复'});await startOutreachDraft(email,input,{ready:()=>false}).completion;expect(get().outreachRuns[0].status).toBe('limited');leadAction(email,{leadId:l.id,action:'block',note:'对方拒绝'});expect(()=>leadAction(email,{leadId:l.id,action:'resume-agent',note:'恢复'})).toThrow('禁止');});
it('legacy suggestion responses also redact provider and review failures',async()=>{const {l}=await setup();for(const failure of [{chatFn:async()=>{throw new Error('api_key=secret-fixture');},review:async()=>[]},{chatFn:async()=> '请说明安装条件',review:async()=>{throw new Error('api_key=secret-fixture');}}]){await expect(generateContactSuggestion(email,{leadId:l.id},{ready:()=>true,...failure})).rejects.toThrow(/未完成/);}});
