import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect,vi} from 'vitest';
import {createHostedService} from './hosted-browser.mjs';
import {readHosted,saveHosted} from './hosted-browser-store.mjs';
import {platformPage,allowedResource} from './hosted-browser-runtime.mjs';
import {readWorkspace,writeWorkspace,publicWorkspace} from './workspace.mjs';
import {commerceAction} from './commerce-workspace.mjs';
import {queueCollection,hostedConnection} from './platform-connector.mjs';
import {importSignals,reviewSignal,leadAction} from './acquisition-workspace.mjs';
import {queueDelivery} from './browser-delivery.mjs';
const email='hosted@example.test',cwd=process.cwd();let dir,svc,rt,loggedIn;
const get=()=>readWorkspace(email).acquisition;
beforeAll(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'harta-hosted-test-'));process.chdir(dir);});
afterAll(()=>{process.chdir(cwd);fs.rmSync(dir,{recursive:true,force:true});});
beforeEach(()=>{fs.rmSync(path.join(dir,'data'),{recursive:true,force:true});writeWorkspace(email,{customers:[{id:'biz',name:'台灯',pitch:'台灯',hunt:'其他行业',packs:[],drops:[]}],ledger:[],contentStates:{},feedback:{}});loggedIn=false;rt={open:vi.fn(async()=>{}),actor:vi.fn(async()=>{if(!loggedIn)throw Object.assign(new Error('请登录'),{status:'login_required'});return {actorId:'self',profileUrl:'https://www.douyin.com/user/self'};}),state:vi.fn(async()=>({cookies:[{name:'fixture',value:'SECRET_SESSION',domain:'.douyin.com',path:'/'}],origins:[]})),frame:vi.fn(async()=>({image:'fixture',width:1280,height:900,url:'https://www.douyin.com/'})),click:vi.fn(async()=>{}),close:vi.fn(async()=>{}),collect:vi.fn(),prepare:vi.fn(async j=>({actorId:'self',text:j.text,targetUserId:j.targetUserId,commentId:j.commentId})),submit:vi.fn(async j=>({status:'succeeded',receipt:{platformId:'new-reply',actorId:'self',targetUserId:j.targetUserId,text:j.text,evidence:'fixture receipt'}})),inbox:vi.fn(async()=>[])};svc=createHostedService({makeRuntime:async()=>rt,available:()=>true,canRun:()=>true});});
afterEach(async()=>{await svc.stop();});
async function start(){const f=await svc.start(email,{customerId:'biz',platform:'抖音'});for(let i=0;i<20&&svc.list(email).connections[0].status==='starting';i++)await new Promise(r=>setTimeout(r,1));return f;}
async function connect(){const f=await start();loggedIn=true;return svc.status(email,{id:f.id});}
it('isolates login frames and never exposes stored session state',async()=>{const f=await start();expect((await svc.status(email,{id:f.id})).status).toBe('login_required');await expect(svc.frame('other@test',{id:f.id})).rejects.toThrow();await expect(svc.click(email,{id:f.id,x:Infinity,y:0})).rejects.toThrow();await svc.click(email,{id:f.id,x:20,y:30});expect(rt.click).toHaveBeenCalledWith(20,30);loggedIn=true;const r=await svc.status(email,{id:f.id});expect(r.status).toBe('connected');expect(r.executionEnabled).toBe(false);expect(hostedConnection(email,r.connectionId).transport).toBe('hosted');await expect(svc.frame(email,{id:f.id})).rejects.toThrow();const publicText=JSON.stringify(svc.list(email))+JSON.stringify(publicWorkspace(readWorkspace(email)));expect(publicText).not.toContain('SECRET_SESSION');expect(fs.readFileSync(path.join(dir,'data/hosted-browser',f.id+'.json'),'utf8')).not.toContain('SECRET_SESSION');});
it('network failures remain failures and can be retried without fake account records',async()=>{rt.open.mockRejectedValueOnce(new Error('net::ERR_CONNECTION_CLOSED'));const f=await start();expect(svc.list(email).connections[0].status).toBe('network_error');expect(get()?.accounts||[]).toHaveLength(0);await svc.retry(email,{id:f.id});await new Promise(r=>setTimeout(r,5));expect((await svc.status(email,{id:f.id})).status).toBe('login_required');});
it('collects through the existing queue with the server-owned connection',async()=>{const f=await connect();commerceAction(email,{action:'target',customerId:'biz',name:'测试账号',platform:'抖音',url:'https://www.douyin.com/user/target'});const j=queueCollection(email,{customerId:'biz',connectionId:f.connectionId,kind:'works',targetId:get().targets[0].id});rt.collect.mockResolvedValue({status:'partial',pageUrl:j.targetUrl,rows:[{url:'https://www.douyin.com/video/123',title:'测试作品'}]});await svc.run(f.id);expect(get().works).toHaveLength(1);expect(get().collectionJobs[0].status).toBe('partial');expect(svc.list(email).connections[0].capabilities.works).toBe('verified');});
async function reply(){const f=await connect();commerceAction(email,{action:'target',customerId:'biz',name:'目标',platform:'抖音',url:'https://www.douyin.com/user/target'});commerceAction(email,{action:'work',customerId:'biz',targetId:get().targets[0].id,title:'台灯',url:'https://www.douyin.com/video/123'});const w=get().works[0];importSignals(email,{customerId:'biz',workId:w.id,source:'测试',rows:[{platform:'抖音',recordId:'c1',authorId:'buyer',authorUrl:'https://www.douyin.com/user/buyer',authorName:'测试买家',url:w.url,text:'台灯多少钱'}]});reviewSignal(email,{signalId:get().signals[0].id,action:'confirm',note:'核对'});let l=get().leads[0];leadAction(email,{action:'draft',leadId:l.id,accountId:get().accounts[0].id,channel:'评论',recipient:w.url,text:'Harta 功能测试'});l=get().leads[0];queueDelivery(email,{connectionId:f.connectionId,kind:'reply',leadId:l.id,messageId:l.messages[0].id,confirmed:true});return f;}
it('actual execution is opt-in, consumes a single permit and persists verified receipt',async()=>{const f=await reply();await svc.run(f.id);expect(rt.submit).not.toHaveBeenCalled();svc.enable(email,{id:f.id,enabled:true});await svc.run(f.id);expect(rt.submit).toHaveBeenCalledTimes(1);expect(get().deliveryJobs[0].status).toBe('succeeded');expect(get().leads[0].messages[0].status).toBe('sent_platform');await svc.run(f.id);expect(rt.submit).toHaveBeenCalledTimes(1);});
it('unknown submission pauses execution and is not retried',async()=>{const f=await reply();svc.enable(email,{id:f.id,enabled:true});rt.submit.mockRejectedValue(new Error('readback lost'));await svc.run(f.id);expect(get().deliveryJobs[0].status).toBe('unknown');expect(svc.list(email).connections[0].executionEnabled).toBe(false);await svc.run(f.id);expect(rt.submit).toHaveBeenCalledTimes(1);});
it('disconnect cancels queued work, clears secrets and rejects late login completion',async()=>{const f=await reply();await svc.disconnect(email,{id:f.id});expect(get().deliveryJobs[0].status).toBe('cancelled');expect(readHosted(f.id,email).storageState).toBeUndefined();expect(()=>hostedConnection(email,f.connectionId)).toThrow();expect(rt.close).toHaveBeenCalled();await svc.run(f.id);expect(rt.submit).not.toHaveBeenCalled();});
it('does not accept arbitrary browser destinations or internal resources',()=>{for(const u of ['http://www.douyin.com/','https://localhost/','https://www.douyin.com.evil.test/','https://user:pass@www.douyin.com/'])expect(()=>platformPage(u,'抖音')).toThrow();expect(allowedResource('http://127.0.0.1:5173/api/me','抖音')).toBe(false);expect(allowedResource('https://p3.douyinpic.com/','抖音')).toBe(false);expect(allowedResource('https://p3.byteimg.com/file','抖音')).toBe(true);});
