import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {beforeAll,afterAll,beforeEach,it,expect} from 'vitest';
import {readWorkspace,writeWorkspace,publicWorkspace} from './workspace.mjs';
import {saveAccount,reviewSignal,leadAction} from './acquisition-workspace.mjs';
import {commerceAction} from './commerce-workspace.mjs';
import {issuePairing,redeemPairing,authenticateConnector,connections,revokeConnection,queueCollection,claimCollection,completeCollection,contactHandoff,cancelCollection,platformUrl} from './platform-connector.mjs';
const email='connector@example.test',root=process.cwd();let dir,account,target,connection,token;
const get=()=>readWorkspace(email).acquisition;
beforeAll(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'harta-connector-test-'));process.chdir(dir);});
afterAll(()=>{process.chdir(root);fs.rmSync(dir,{recursive:true,force:true});});
beforeEach(()=>{fs.rmSync(path.join(dir,'data'),{recursive:true,force:true});writeWorkspace(email,{customers:[{id:'c1',name:'灯具',pitch:'台灯',packs:[],drops:[]}],ledger:[],feedback:{},contentStates:{}});saveAccount(email,{customerId:'c1',name:'我的账号',platform:'抖音'});account=get().accounts[0];commerceAction(email,{action:'target',customerId:'c1',platform:'抖音',name:'目标账号',url:'https://www.douyin.com/user/author1',recordId:'author1'});target=get().targets[0];const paired=redeemPairing({code:issuePairing(email,{accountId:account.id}).code});token=paired.token;connection=authenticateConnector(token);});
function queue(kind='works',extra={}){return queueCollection(email,{connectionId:connection.id,customerId:'c1',targetId:target.id,kind,...extra});}
function finish(rows,status='partial'){const job=claimCollection(connection);return completeCollection(connection,{jobId:job.id,lease:job.lease,pageUrl:job.targetUrl,rows,status});}
function work(){queue();finish([{url:'https://www.douyin.com/video/123',title:'台灯怎么选'}]);return get().works[0];}
const comment={recordId:'comment1',text:'想买台灯，多少钱？',authorName:'小夏',authorUrl:'https://www.douyin.com/user/buyer1',publishedText:'昨天',ipRegion:'浙江'};
it('one-use pairing and private, revocable credentials',()=>{const p=issuePairing(email,{accountId:account.id});redeemPairing({code:p.code});expect(()=>redeemPairing({code:p.code})).toThrow();expect(()=>issuePairing('other@test',{accountId:account.id})).toThrow();expect(JSON.stringify(connections(email))).not.toContain(token);expect(JSON.stringify(publicWorkspace(readWorkspace(email)))).not.toContain('tokenHash');expect(()=>revokeConnection('other@test',{connectionId:connection.id})).toThrow();revokeConnection(email,{connectionId:connection.id});expect(()=>authenticateConnector(token)).toThrow();});
it('rejects cross-business jobs, hostile URLs and wrong result pages',()=>{expect(()=>queue('works',{customerId:'other'})).toThrow();for(const u of ['https://www.douyin.com.evil.test/video/123','https://user:pass@www.douyin.com/video/123','http://www.douyin.com/video/123'])expect(()=>platformUrl(u,'抖音','work')).toThrow();queue();const j=claimCollection(connection);expect(()=>completeCollection(connection,{jobId:j.id,lease:j.lease,status:'partial',pageUrl:'https://www.douyin.com/user/other',rows:[]})).toThrow('来源');expect(()=>completeCollection(connection,{jobId:j.id,lease:'wrong',status:'partial',pageUrl:j.targetUrl,rows:[]})).toThrow();});
it('imports works and comments with identity, scope and repeat deduplication',()=>{const w=work();queue('comments',{workId:w.id});expect(finish([comment]).added).toBe(1);let s=get().signals[0];expect(s.sourceType).toBe('browser_visible');expect(s.authorId).toBe('buyer1');expect(s.authorUrl).toContain('/user/buyer1');expect(s.publishedAt).toBe('');queue('comments',{workId:w.id});expect(finish([comment]).duplicate).toBe(1);expect(get().signals).toHaveLength(1);reviewSignal(email,{signalId:s.id,action:'confirm',note:'核对原话'});const lead=get().leads[0];const handoff=contactHandoff(email,{leadId:lead.id,channel:'私信'});expect(handoff.url).toBe(comment.authorUrl);expect(handoff.sent).toBe(false);leadAction(email,{leadId:lead.id,action:'block',note:'对方拒绝联系'});expect(()=>contactHandoff(email,{leadId:lead.id})).toThrow();});
it('does not invent timestamps or count author replies as leads',()=>{const w=work();queue('comments',{workId:w.id,since:'2020-01-01'});expect(finish([comment]).filtered).toBe(1);expect(get().signals).toHaveLength(0);queue('comments',{workId:w.id});finish([{...comment,authorUrl:target.url}]);const s=get().signals[0];expect(s.isAuthorReply).toBe(true);expect(()=>reviewSignal(email,{signalId:s.id,action:'confirm',note:'作者回复'})).toThrow();});
it('cancelled jobs reject late results, and failed reads cannot import rows',()=>{queue();const j=claimCollection(connection);expect(()=>completeCollection(connection,{jobId:j.id,lease:j.lease,pageUrl:j.targetUrl,status:'login_required',rows:[{url:'https://www.douyin.com/video/1'}]})).toThrow();cancelCollection(email,{jobId:j.id});expect(()=>completeCollection(connection,{jobId:j.id,lease:j.lease,pageUrl:j.targetUrl,status:'partial',rows:[]})).toThrow();expect(get().works).toHaveLength(0);});
it('DOM fingerprints deduplicate without presenting themselves as platform IDs',()=>{const w=work();queue('comments',{workId:w.id});finish([{...comment,recordId:''}]);queue('comments',{workId:w.id});expect(finish([{...comment,recordId:''}]).duplicate).toBe(1);expect(get().signals[0].identitySource).toBe('dom_fingerprint');});
