const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function allowed(raw,platform){const u=new URL(raw),domain=platform==='抖音'?'douyin.com':platform==='小红书'?'xiaohongshu.com':'';if(!domain||u.protocol!=='https:'||![`www.${domain}`,`creator.${domain}`].includes(u.hostname)||u.port||u.username||u.password)throw new Error('执行网址不属于指定平台');return u;}
async function page(raw,platform){const url=allowed(raw,platform),tabs=await chrome.tabs.query({url:`${url.origin}/*`});let t=tabs.find(t=>{try{return new URL(t.url).pathname===url.pathname;}catch{return false;}});if(!t)t=await chrome.tabs.create({url:url.href,active:false});for(let n=0;n<60;n++){if((await chrome.tabs.get(t.id)).status==='complete')break;await sleep(500);}await sleep(1000);await chrome.scripting.executeScript({target:{tabId:t.id},files:['delivery.js']});return t.id;}
async function execute(tabId,op,args){const [r]=await chrome.scripting.executeScript({target:{tabId},func:async(op,args)=>{try{return {value:await globalThis.hartaDelivery[op](...args)};}catch(e){return {error:e.message,status:e.status||'unsupported'};}},args:[op,args]});if(r?.result?.error)throw Object.assign(new Error(r.result.error),{status:r.result.status});if(!r?.result)throw new Error('页面执行未返回');return r.result.value;}
async function identity(c){const url=c.platform==='抖音'?'https://www.douyin.com/':'https://www.xiaohongshu.com/explore',id=await page(url,c.platform);return execute(id,'actor',[]);}
async function stashReceipt(c,payload){const {deliveryReceipts=[]}=await chrome.storage.local.get('deliveryReceipts');await chrome.storage.local.set({deliveryReceipts:[...deliveryReceipts.filter(v=>!(v.connectionId===c.id&&v.payload.jobId===payload.jobId)),{connectionId:c.id,payload}]});}
export async function flushReceipts(c,request){const {deliveryReceipts=[]}=await chrome.storage.local.get('deliveryReceipts');for(const entry of deliveryReceipts.filter(v=>v.connectionId===c.id)){await request(c,'delivery-complete',entry.payload);const latest=await chrome.storage.local.get('deliveryReceipts');await chrome.storage.local.set({deliveryReceipts:(latest.deliveryReceipts||[]).filter(v=>!(v.connectionId===c.id&&v.payload.jobId===entry.payload.jobId))});}}
export async function runDelivery(c,request){const {job}=await request(c,'delivery-claim');if(!job)return;let authorized=false,result;
 try{const actor=await identity(c);if(actor.actorId!==job.expectedActorId)throw new Error('当前浏览器账号与任务绑定账号不同');const tab=await page(job.targetUrl,c.platform),assets=[];for(const assetId of job.assetIds||[]){const asset=await request(c,'delivery-asset',{jobId:job.id,lease:job.lease,assetId}),size=4*1024*1024,total=Math.ceil(asset.base64.length/size),meta={id:asset.id,name:asset.name,mime:asset.mime};for(let index=0;index<total;index++)await execute(tab,'assetChunk',[meta,asset.base64.slice(index*size,(index+1)*size),index,total]);assets.push(meta);}
 const evidence=await execute(tab,'prepare',[job,actor.actorId,assets]);
 const fresh=await identity(c);if(fresh.actorId!==actor.actorId)throw new Error('提交前登录账号发生变化');
 const {executeDelivery=false}=await chrome.storage.local.get('executeDelivery');if(!executeDelivery)throw new Error('已关闭实际执行开关');
 await request(c,'delivery-authorize',{jobId:job.id,lease:job.lease,evidence});authorized=true;
 result=await execute(tab,'submit',[job]);
 }catch(e){result={status:authorized?'unknown':e.status||'unsupported',error:e.message};}
 await stashReceipt(c,{jobId:job.id,lease:job.lease,...result});await flushReceipts(c,request);
}
export async function runMonitors(c,request){const {rules=[]}=await request(c,'delivery-monitors');if(!rules.length)return;const actor=await identity(c);for(const rule of rules){try{if(actor.actorId!==rule.expectedActorId)throw new Error('自动回复账号与当前登录不一致');const tab=await page(rule.scopeUrl,c.platform),rows=await execute(tab,'inbox',[rule]);await request(c,'delivery-events',{ruleId:rule.id,revision:rule.revision,actorId:actor.actorId,pageUrl:rule.scopeUrl,rows});}catch(e){await request(c,'delivery-monitor-error',{ruleId:rule.id,error:e.message});}}}
