const $=id=>document.getElementById(id),status=$('status');
const message=payload=>chrome.runtime.sendMessage(payload).then(r=>{if(r?.error)throw new Error(r.error);return r;});
async function render(){const {connections=[],autoRead=false,executeDelivery=false}=await chrome.storage.local.get(['connections','autoRead','executeDelivery']);$('auto').checked=autoRead;$('delivery').checked=executeDelivery;$('setup').open=!connections.length;$('connections').replaceChildren();for(const c of connections){const box=document.createElement('section');box.className='connection';const title=document.createElement('strong');title.textContent=`${c.platform} · ${c.name}`;const note=document.createElement('small');note.textContent=`${c.origin} · ${c.lastChecked?'上次检查 '+new Date(c.lastChecked).toLocaleTimeString():'尚未读取'}\n浏览器已配对，平台登录状态以平台页面为准`;const error=document.createElement('p');error.className='error';error.textContent=c.error||'';const remove=document.createElement('button');remove.textContent='移除此浏览器连接';remove.onclick=async()=>{await message({action:'forget',id:c.id});await render();};box.append(title,note,error,remove);$('connections').append(box);}}
$('pair').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const u=new URL($('origin').value);if(u.username||u.password||u.pathname!=='/'||u.search||u.hash||!(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname))))throw new Error('请输入 HTTPS 工作台地址或本机 localhost 地址');const granted=await chrome.permissions.request({origins:[`${u.protocol}//${u.hostname}/*`,'https://www.douyin.com/*','https://www.xiaohongshu.com/*','https://creator.douyin.com/*','https://creator.xiaohongshu.com/*']});if(!granted)throw new Error('需要允许访问工作台与两个平台，才能执行读取任务');await message({action:'pair',origin:u.origin,code:$('code').value,deviceName:$('device').value});$('code').value='';status.textContent='已配对。回 Harta 选择目标账号或作品，发起读取。';await render();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};
$('auto').onchange=()=>chrome.storage.local.set({autoRead:$('auto').checked});
$('run').onclick=async()=>{$('run').disabled=true;status.textContent='正在检查任务；平台需要登录或验证时，请在相应标签页处理。';try{await message({action:'run'});status.textContent='已检查任务，请查看下方连接状态与 Harta 任务记录。';await render();}catch(e){status.textContent=e.message;}finally{$('run').disabled=false;}};
render();

$('delivery').onchange=async()=>{try{if($('delivery').checked){const ok=await chrome.permissions.request({origins:['https://creator.douyin.com/*','https://creator.xiaohongshu.com/*']});if(!ok)throw new Error('需要允许访问平台创作者页面');}await chrome.storage.local.set({executeDelivery:$('delivery').checked});}catch(e){$('delivery').checked=false;status.textContent=e.message;}};
